<?php

/**
 * Implementation of hook_block_info().
 */
function blex1_block_info() {
  $blocks ['my-block-id'] = array(
      'info' => t('3Q Vejret')
  );
  return $blocks;
}

function blex1_help($path, $arg) {
  switch ($path) {
    case "admin/help#blex" :
      return '<p>' . t("Displays vejr") . '</p>';
      break;
  }
}

/**
 * Implementation of hook_block_view().
 */
function blex1_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'my-block-id' :
      $block ['subject'] = 'Vejret i 3Q ';
      $block ['content'] = blex1_contents();
      break;
  }
  return $block;
}


function blex1_contents() {
$json_string = 'https://api.weatherlink.com/v1/NoaaExt.json?user=001D0A00066D&pass=1333qe&apiToken=D6AC2FFEF2384221A7134C7AFCE5926E';
$jsondata = file_get_contents($json_string);
$obj = json_decode($jsondata, true);
$ptemp = ($obj['davis_current_observation']['temp_extra_1']);
$pool =  "Pool (C): " .  number_format((($ptemp -32)/ 1.8), 1) . "<br>";
$temp = "Temp (C): " . ($obj['temp_c']) . "<br>";
$fugt =  "Fugt (%RH): " . ($obj['relative_humidity']) . "<br>";
$baro =  "Tryk (mB): " . ($obj['pressure_mb']) . "<br>";
$vind =  "Vind (km/t): " . ($obj['wind_kt']) . "<br>";
// echo "Retning: " . ($obj['wind_dir']) . "<br>";
$dato = ($obj['observation_time']) . "<br>";

  $vejrdata = $temp . $fugt . $baro . $vind . $pool;

  return $vejrdata . "<br>$dato<br>";
}
