<?php

/**
 * Implementation of hook_block_info().
 */
function blex_block_info() {
	$blocks ['my-block-id'] = array (
			'info' => t ( '3Q Vejret' )
	);
	return $blocks;
}
function blex_help($path, $arg) {
	switch ($path) {
		case "admin/help#blex" :
			return '<p>' . t ( "Displays vejr" ) . '</p>';
			break;
	}
}

/**
 * Implementation of hook_block_view().
 */
function blex_block_view($delta = '') {
	$block = array ();
	switch ($delta) {
		case 'my-block-id' :
			$block ['subject'] = 'Vejret i 3Q ';
			$block ['content'] = blex_contents ();
			break;
	}
	return $block;
}

/**
 * custom html block
 *
 * @return string
 */
function blex_contents() {
	define ( "URL", 'http://www.weatherlink.com/user/3q/index.php?view=summary&headers=1' );
	define ( "Davis", 'http://www.weatherlink.com/user/3q/index.php?view=summary&headers=1' );
	define ( "Merelink", "<a href=" . Davis . " target=\"_blank\">Mere vejr?</a>" );
	define ( "EXTRA2", "93" );

	$html = file_get_html ( URL );
	$element = $html->find ( "td.summary_data" );
	$temp = $element [0 * 7 + 1]->innertext;
	$fugt = $element [1 * 7 + 0]->innertext;
	$baro = $element [6 * 7 + 1]->innertext;
	$vind = $element [9 * 6 + 1]->innertext;

	if (strcasecmp ( $vind, "Calm" ) == 0) {
		$vind = "Rolig";
	}

	$regn = $element [82]->innertext;

	if (sizeof ( $element ) > EXTRA2) {
		$pool = $element [EXTRA2]->innertext;
	} else {
		$pool = " ---";
	}

	$format = "Temp: %s <br>" . "Fugt: %s <br>" . "Tryk: %s <br>" . "Vind: %s <br>" . "Regn: %s <br>" . "Pool: %s <br>";
	$vejrdata = sprintf ( $format, $temp, $fugt, $baro, $vind, $regn, $pool );

	$element = $html->find ( "td.summary_timestamp" );
	$dato = $element [0]->innertext;
	$re = "/ ([0-9]+):([0-9]+)/";
	preg_match ( $re, $dato, $matches );

	// ini_set ( "date.timezone", "Europe/Copenhagen" );
	$dato = $matches [0];
	return $vejrdata . "<br>Opdateret $dato<br>" . Merelink;
}
